### ISSUE TITLE
[QUESTION] README doesn't specify how the library handles drawings, handwriting, etc.

### ISSUE THREAD

**Issue by madCode** [ChristosMylonas/onenote2md#1]
Sorry to leave an issue! It's the only way to ask a question on repos on github, it looks like. I'm really excited to use this library! I just have one question: how does it handle drawings/sketches/handwriting that might be in a one note document?

**Comment by ChristosMylonas** [comment]
They are not currently handled as separate objects. I'm experimenting with exporting them as images in upcoming release.

**Comment by madCode** [comment]
@ChristosMylonas I see. So are they currently skipped? Like if I convert a document that has images in it to a markdown file using this library, will the text remain and the images/handwriting will be missing? Just want to make sure I know the functionality here. It also might be worth updating the README to clarify this, but up to you. Thanks again for your time! It's much appreciated.
