### ISSUE TITLE
'Onenote2md.Cmd' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by SuperFelix117** [ChristosMylonas/onenote2md#2]
I opened cmd in the onenote2md-master directory, and typed Onenote2md.Cmd. Why does it say:
'Onenote2md.Cmd' is not recognized as an internal or external command, operable program or batch file?

Thanks

**Comment by SuperFelix117** [comment]
<img width="446" alt="Screenshot 2021-02-06 110437" src="https://user-images.githubusercontent.com/19553061/107107276-1e0eae00-686b-11eb-884e-c4cb61493307.png">

**Comment by kevindurston21** [comment]
Hi SuperFelix117,

I just started looking at this programme today and still getting my head around it, it is very good.  Christos has done a great job.

It needs to be compiled to an exe to be used and I'm guessing that that is the issue.

If you have not done any C# development before then these steps would get you there.

- Fork this repository in github
- Download visual studio Community 2019 from Microsoft and in the installer choose what you like but you'll need 

> .NET desktop development Build WPF, Windows Forms, and console applications using C#, Visual Basic, and F# with .NET Core and .NET Framework.
> ![net_desktop](https://user-images.githubusercontent.com/43143552/107589865-d1c2c580-6bfe-11eb-8169-11b8a1c8184c.jpg)

- In visual studio when it starts there is an option to pull in a git hub repository
    - enter the address of **your** forked repository
- Choose build --> Build Solution from the visual studio menu
- exe will be in `C:\Users\your-user-name\source\repos\onenote2md\Onenote2md.Cmd\bin\Debug`

Obviously, that makes it sound very easy but you'll probably need to do some 'Googling' if you have not done it before.  Great way to learn.

Hope this helped.

Kevin

**Comment by SuperFelix117** [comment]
thx kevin!! Nice explanation

**Comment by lucidBrot** [comment]
It would be nice if the executable were provided as a downloadable release on here. I don't really know what I'm doing but here's my `Debug` directory containing the executable and what I think are potentially required libraries that were also created in that folder by Visual Studio.  

[Debug.zip](https://github.com/ChristosMylonas/onenote2md/files/6017970/Debug.zip)  

The results look great. It works way better for tables and highlights (that aren't plain markdown) than what was suggested in https://github.com/foambubble/foam/issues/151 so I think I'm going with this 😊

**Comment by ChristosMylonas** [comment]
Hello @lucidBrot,
Version 1.0 is tagged and released at https://github.com/ChristosMylonas/onenote2md/releases/tag/v1.0
