### ISSUE TITLE
How can I actually build an executable with the code provided

### ISSUE THREAD

**Issue by fieldrabbit21** [ChristosMylonas/onenote2md#8]
Hi this is a question from a noob. How can I actually build an executable with the code provided? I have VS (community version)

**Comment by juanbretti** [comment]
Same question here.
Thanks!

**Comment by Argimko** [comment]
You need to open `Onenote2md.Solution\onenote2md solution.sln` file at VS then build `Onenote2md.Tester` and `Onenote2md.Cmd` projects.

`Onenote2md.Tester` is usefulf form to play with your OneNote notebooks

Also, keep in mind that there is useful Pull request in this repo https://github.com/ChristosMylonas/onenote2md/pull/5 – you may need manually add this code to the project

**Comment by Argimko** [comment]
Also I could recommend to try one more converter – https://github.com/alxnbl/onenote-md-exporter
